cc_test(
    name = "spec",
    srcs = [
        "stream_utils_spec.cpp",
    ],
    deps = [
        "//core",
        "//core/spec:test_utils",
        "//core/stream",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
