cc_test(
    name = "spec",
    srcs = [
        "category_filter_spec.cpp",
    ],
    deps = [
        "//core/categories",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
