cc_library(
    name = "arguments",
    srcs = ["parser.cpp"],
    hdrs = ["parser.h"],
    visibility = [
        "//cmd:__pkg__",
        "//gui:__pkg__",
    ],
    deps = [
        "@boost//:program_options",
    ],
)
