cc_test(
    name = "spec",
    srcs = [
        "tracker_spec.cpp",
    ],
    deps = [
        "//core",
        "//core/spec:test_utils",
        "//core/stream",
        "//parser",
        "//tracker",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
