cc_test(
    name = "spec",
    srcs = [
        "bar_series_converter.cpp",
        "completer_spec.cpp",
    ],
    deps = [
        "//gui:my_widget",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
