cc_library(
    name = "stream",
    srcs = [
        "utils.cpp",
    ],
    hdrs = [
        "utils.h",
    ],
    visibility = [
        "//core/categories:__subpackages__",
        "//core/stream:__subpackages__",
        "//parser:__subpackages__",
        "//tracker:__subpackages__",
    ],
    deps = [
        "//core",
    ],
)
